name: v1checkmate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  jwt_decode: ^0.3.1
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8

  cunning_document_scanner: ^1.3.1
  permission_handler: ^12.0.0+1
  pdf: ^3.11.0
  path_provider: ^2.1.4
  file_saver: ^0.3.1 # Check for the latest version
  syncfusion_flutter_pdfviewer: ^31.2.5
  jwt_decoder: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
